jscicd:
  envVars:
    - FOO=BAR
    - TEST=YES
  stages:
    exampleStageName3:
      zx:
        - let example = "test"
        - await $`apt -y install texlive-base`
        - await $`mkdir ${example}`
    stageName2:
      fromFile: asd.mjs
